### ISSUE TITLE
gst-pylonsrc not found

### ISSUE THREAD

**Issue by viktorvorobev** [zingmars/gst-pylonsrc#3]
I tried to install your package by following the instructions:
1. `autogen.sh`
2. `make`
3. `sudo make install`  

and everything compiled fine, but gst-inspect can not find pylonsrc, and I'm not sure why.
I can clearly see `libgstpylonsrc.la` and `libgstpylonsrc.so` files in `/usr/local/lib/gstreamer1.0` directory, and this folder is added to both PATH and LD_LIBRARY_PATH.

I am using gstreamer 1.8.3 and Ubuntu 16.04, can you please help me? Thank you

**Comment by zingmars** [comment]
Sure.

Generally after installing gstreamer plugins you need to reset gstreamer's cache. To do so you can just delete the cache folder, [usually located in `$HOME/.cache/gstreamer-1.0`](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstRegistry.html) (you can just rm -rf the folder). Afterwards you can run `gst-inspect-1.0` again to reset cache and it should show up. 

If it does not, the problem might lie in the fact that you're using the version of gstreamer distributed by Ubuntu from their apt repositories (I'm guessing from the fact that you're using gstreamer 1.8.3) . Now I might be wrong, but it's probably looking for the plugins in a different place ([`/usr/lib/x86_64-linux-gnu/gstreamer-1.0`](https://packages.ubuntu.com/xenial/amd64/gstreamer1.0-plugins-good/filelist)). You can try moving the files there and resetting the cache. You can also try [`$HOME/.local/share/gstreamer-1.0`](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gst-running.html).

Also, to verify that the plugin compiled and linked properly you can test it (instead of just checking if the file exists) with  `gst-inspect-1.0 /path/to/file`, i.e. `gst-inspect-1.0 /usr/local/lib/gstreamer-1.0/libgstpylonsrc.la`. If it returns the information about the plugin (name, class inheritance diagram) then it's fine. If it returns an error, then obviously something's wrong.

**Comment by viktorvorobev** [comment]
Thank you very much! I've moved `libgstpylonsrc.*` to `/usr/lib/x86_64-linux-gnu/gstreamer-1.0` and now everything works fine now.
